### ISSUE TITLE
Appointment mistakenly brought forward by 2 hours

### ISSUE THREAD

**Issue by Max-vS** [TUM-Dev/CalendarProxy#139] opened 2023-03-28 21:03 UTC
The time periods of the individual courses are 2 hours too early and this is also the case with all fellow students I have asked so far.

**Comment by joschahenningsen** [comment] 2023-03-28 21:10
Are you (and your fellow students) using iOS by chance?

**Comment by Max-vS** [comment] 2023-03-28 22:07
Yes!

**Comment by joschahenningsen** [comment] 2023-03-30 11:44
This is a regression that was fixed in #128. However, the new version builds a docker container with another name that the server doesn't recognize and therefore the fix was never deployed. I'm taking care of it :)

**Comment by joschahenningsen** [comment] 2023-03-30 11:58
I deployed the latest version to the server. Can you please remove the calendar from your phone, add it again and tell me whether the issue is fixed? @Max-vS  :)

**Comment by Max-vS** [comment] 2023-03-30 12:42
Will do. Thanks a lot!

**Comment by Max-vS** [comment] 2023-04-01 15:54
Now it works as intended, thanks!

**Closed** 2023-04-01 17:09 UTC
